### ISSUE TITLE
windowsでビルドエラー

### ISSUE THREAD

**Issue by hshindo** [paperai/paperanno-ja#7]
anno: prepareが原因．

**Comment by yoheiMune** [comment]
不具合あり申し訳ありません。
unixベースのパスになっているところがいくつかありますのでその辺を修正します。
あいにく現在手元にWindows機がないので手配します。
よろしくお願いします。

**Comment by yoheiMune** [comment]
お世話になっております。
Windows環境でもビルド処理ができるように修正しました。Windowsサーバー上でも動作確認したので問題ないと思いますが何か不備ありましたらご指摘ください。
また今回の対応でWindowsとMacなど複数環境に対応するために、gulpを導入しています。

変更内容はこちらです。
https://github.com/paperai/paperanno/pull/3/files

どうぞよろしくお願いします。

**Comment by hshindo** [comment]
npm install
npm run anno:build
だとエラーになりますが，何か手順が違うのでしょうか？

**Comment by yoheiMune** [comment]
いえ、その手順で合っています。お手数ですが上記コマンド実行時の出力内容をいただけないでしょうか？
またWindowsではコマンドプロンプトでの実行になりますでしょうか？
お忙しいところすみません、よろしくお願いします。

**Comment by hshindo** [comment]
コマンドプロンプトです．
cloneし直してinstallしました．
npm install
npm run anno:build


出力：
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\hshindo\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'anno:build' ]
2 info using npm@4.0.3
3 info using node@v4.5.0
4 verbose run-script [ 'preanno:build', 'anno:build', 'postanno:build' ]
5 info lifecycle paperanno@1.0.0~preanno:build: paperanno@1.0.0
6 silly lifecycle paperanno@1.0.0~preanno:build: no script for preanno:build, continuing
7 info lifecycle paperanno@1.0.0~anno:build: paperanno@1.0.0
8 verbose lifecycle paperanno@1.0.0~anno:build: unsafe-perm in lifecycle true
9 verbose lifecycle paperanno@1.0.0~anno:build: PATH: C:\Users\hshindo\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Users\hshindo\Documents\GitHub\paperanno\node_modules\.bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\libnvvp;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5\libnvvp;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64_win\mpirt;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64_win\compiler;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5\nvvm\bin;C:\Program Files (x86)\CMake\bin;C:\Program Files\Git LFS;C:\Program Files\EmEditor;C:\Program Files\NVIDIA Corporation\NVSMI;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files\nodejs\;C:\Program Files (x86)\Skype\Phone\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\LyX 2.2\Perl\bin;C:\Program Files (x86)\Pandoc\;C:\Users\hshindo\AppData\Local\Programs\EmEditor;C:\Python27;C:\Python27\Scripts;C:\Users\hshindo\AppData\Local\atom\bin;C:\mingw64\bin;C:\dev\eigen-3.2.8\Eigen;C:\texlive\2015\bin\win32;C:\Hugo\bin;C:\Users\hshindo\AppData\Local\Julia-0.5.0\bin;C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin;C:\Program Files (x86)\MeCab\bin;C:\Users\hshindo\AppData\Roaming\npm;%USERPROFILE%\AppData\Local\Microsoft\WindowsApps;
10 verbose lifecycle paperanno@1.0.0~anno:build: CWD: C:\Users\hshindo\Documents\GitHub\paperanno
11 silly lifecycle paperanno@1.0.0~anno:build: Args: [ '/d /s /c', 'npm run anno:prepare && webpack' ]
12 silly lifecycle paperanno@1.0.0~anno:build: Returned: code: 1  signal: null
13 info lifecycle paperanno@1.0.0~anno:build: Failed to exec anno:build script
14 verbose stack Error: paperanno@1.0.0 anno:build: `npm run anno:prepare && webpack`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\hshindo\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\hshindo\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:829:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid paperanno@1.0.0
16 verbose cwd C:\Users\hshindo\Documents\GitHub\paperanno
17 error Windows_NT 10.0.14393
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\hshindo\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "anno:build"
19 error node v4.5.0
20 error npm  v4.0.3
21 error code ELIFECYCLE
22 error paperanno@1.0.0 anno:build: `npm run anno:prepare && webpack`
22 error Exit status 1
23 error Failed at the paperanno@1.0.0 anno:build script 'npm run anno:prepare && webpack'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the paperanno package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run anno:prepare && webpack
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs paperanno
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls paperanno
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by yoheiMune** [comment]
ありがとうございます。調査します！

**Comment by yoheiMune** [comment]
お世話になっております。
確認しましたところ、nodeのバージョン違いの問題でした。node v4.5.0ですと、gulpfile.js内で使っていたECMAScript6の記法（let構文など）が動作しない状態でしたので、その辺りを修正しました。

大変お手数ですが再度ご確認をお願いできますでしょうか？
よろしくお願いします。

**Comment by hshindo** [comment]
確認致しました．
ついでにnodeのバージョンが古かったようなのでアップグレードしました．
今後は，古いバージョンに対応する必要はあまりないので，ECMAScript6の構文を使っていただいて構いません．
よろしくお願いします．

**Comment by hshindo** [comment]
１点お伺いしたいのですが，
paperannoはクライアントアプリなので，サーバーは特に必要ないと認識していますが，その場合でもnode.jsのnpm run buildのようなことをしないと使えないのでしょうか？

単純にgit clone paperannoをして，その中のindex.htmlをブラウザで開けば，現在のデモのような画面が出てくるほうが好ましいのですが，いかがでしょうか？

**Comment by yoheiMune** [comment]
ご確認ありがとうございます。

> paperannoはクライアントアプリなので，サーバーは特に必要ないと認識していますが，その場合でもnode.jsのnpm run buildのようなことをしないと使えないのでしょうか？

いえ、基本的には `docs/index.html`をブラウザで開けば利用することができます。
ただしダブルクリックなどで開く場合にはブラウザのセキュリティ制約上動作しない場合があります（ChromeやFirefoxの場合にはpdfファイルをAjaxで取得するところで失敗します。Safariでは動きます）

> npm run anno:build

こちらはソースコードを変更する（=開発する）場合に使います。 `git cone`後に表示するだけであれば利用は不要です。

分かりづらい点がありましたら是非ご指摘ください。
よろしくお願いします。

**Comment by yoheiMune** [comment]
あっあと申し訳ありません。

```
$ npm run anno:publish
```
こちらでビルド処理をお願いできますでしょうか？
`npm run anno:build`に加え、 `docs/`以下へのファイルの配置も行います。
（Readmeは後ほど変更します）

すみませんがよろしくお願いします。

**Comment by yoheiMune** [comment]
Readmeにも追記しました（anno:publishと、nodeのバージョンについて）。
https://github.com/paperai/paperanno

よろしくお願いします。

**Comment by hshindo** [comment]
有難うございます．これでＯＫです．

**Comment by yoheiMune** [comment]
確認ありがとうございました。
